const KEY='lucas_content_manager_v01';
let state=JSON.parse(localStorage.getItem(KEY)||'{}');
let mode='READY', chip='', editing=null;
const $=s=>document.querySelector(s);
function merged(x){const o=state[x.id]||{};return {...x,...o,beats:o.beats||x.beats};}
function save(){localStorage.setItem(KEY,JSON.stringify(state)); $('#localState').textContent=Object.keys(state).length?'LOCAL EDITS · '+Object.keys(state).length:'';}
function setStatus(id,status){state[id]={...(state[id]||{}),status};save();render();}
function card(x){const d=merged(x); const ready=d.status==='READY_TO_SHOOT'; const filmed=d.status==='RECORDED'; const beats=(d.beats||[]).filter(Boolean).map(v=>`<li>${esc(v)}</li>`).join(''); const graphics=(d.graphics||[]).filter(Boolean).map(v=>`<span class="graphic">✦ ${esc(v)}</span>`).join(''); return `<article class="card" data-id="${d.id}"><div class="meta"><span class="tag">${d.id}</span><span class="tag ${ready?'ready':d.status==='IDEA'?'idea':''}">${esc(d.status)}</span><span class="tag">${esc(d.type)}</span><span class="tag">${esc(d.collab)}</span>${d.duration?`<span class="tag">${esc(d.duration)}</span>`:''}</div><h2 class="title">${esc(d.title)}</h2>${ready?`<div class="hook">“${esc(d.hook)}”</div>`:`<div class="small">Todavía no está listo para filmar. Falta desarrollar hook + fact + beats.</div>`}<div class="card-buttons"><button onclick="toggleCard('${d.id}')">${ready?'🎬 Ver tarjeta':'👀 Ver'}</button>${ready?`<button class="${filmed?'good':''}" onclick="setStatus('${d.id}','${filmed?'READY_TO_SHOOT':'RECORDED'}')">${filmed?'↩ Volver a READY':'✓ Filmado'}</button>`:''}${ready?`<button onclick="editCard('${d.id}')">✎ Editar</button>`:''}</div><div class="details">${d.fact?`<div class="fact"><b>FACT</b><br>${esc(d.fact)}</div>`:''}${beats?`<ol class="beats">${beats}</ol>`:''}${d.close?`<div class="close">CIERRE · ${esc(d.close)}</div>`:''}${graphics?`<div class="small">GRÁFICOS</div><div class="graphics">${graphics}</div>`:''}<div class="card-buttons"><a class="btn" href="https://drive.google.com/drive/folders/1Nof2AnkaNgU-PB1yX44k611B1XduDwbW" target="_blank">🖼 Multimedia</a>${d.source?`<a class="btn" href="${d.source}" target="_blank">↗ Fuente</a>`:''}</div></div></article>`;}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(){const q=$('#search').value.toLowerCase().trim(); let arr=BASE.map(merged).sort((a,b)=>a.queue-b.queue); if(mode==='READY') arr=arr.filter(x=>x.status==='READY_TO_SHOOT'); if(chip==='PRACTICO'||chip==='OPINION') arr=arr.filter(x=>x.type===chip); if(chip==='COLLAB') arr=arr.filter(x=>x.collab.includes('CHIMI')); if(chip==='RECORDED') arr=arr.filter(x=>x.status==='RECORDED'); if(chip==='IDEA') arr=arr.filter(x=>x.status==='IDEA'); if(q) arr=arr.filter(x=>JSON.stringify(x).toLowerCase().includes(q)); $('#list').innerHTML=arr.length?arr.map(card).join(''):`<div class="empty">No hay tarjetas con este filtro.</div>`; const all=BASE.map(merged); const r=all.filter(x=>x.status==='READY_TO_SHOOT').length, f=all.filter(x=>x.status==='RECORDED').length; $('#stats').textContent=`${arr.length} visibles · ${r} ready · ${f} filmados · ${all.length} total`; $('#filterReady').classList.toggle('active',mode==='READY'); $('#filterAll').classList.toggle('active',mode==='ALL'); document.querySelectorAll('[data-chip]').forEach(b=>b.classList.toggle('active',b.dataset.chip===chip)); save();}
window.toggleCard=id=>{document.querySelector(`[data-id="${id}"]`).classList.toggle('open')}; window.setStatus=setStatus;
window.editCard=id=>{editing=id; const d=merged(BASE.find(x=>x.id===id)); $('#editTitle').textContent=id+' · Editar'; $('#eHook').value=d.hook||''; $('#eFact').value=d.fact||''; $('#eB1').value=d.beats?.[0]||''; $('#eB2').value=d.beats?.[1]||''; $('#eB3').value=d.beats?.[2]||''; $('#eClose').value=d.close||''; $('#modal').classList.add('open');};
$('#saveEdit').onclick=()=>{state[editing]={...(state[editing]||{}),hook:$('#eHook').value,fact:$('#eFact').value,beats:[$('#eB1').value,$('#eB2').value,$('#eB3').value],close:$('#eClose').value}; save(); $('#modal').classList.remove('open'); render();};
$('#closeModal').onclick=()=>$('#modal').classList.remove('open'); $('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')}; $('#filterReady').onclick=()=>{mode='READY';chip='';render()}; $('#filterAll').onclick=()=>{mode='ALL';chip='';render()}; $('#search').oninput=render; document.querySelectorAll('[data-chip]').forEach(b=>b.onclick=()=>{chip=chip===b.dataset.chip?'':b.dataset.chip;mode='ALL';render()}); $('#resetBtn').onclick=()=>{if(confirm('¿Borrar estados y ediciones guardados solamente en este teléfono?')){state={};save();render();}}; render();
